### ISSUE TITLE
No perf_mode file in sysfs [Surface Pro 2017 - m3 7Y30 4GB]

### ISSUE THREAD

**Issue by PJungkamp** [linux-surface/surface-control#14]
Running `surface performance get` yields:
```
Error: Failed to get current performance mode

Caused by:
    0: Could not access device "/sys/bus/surface_aggregator/devices/01:03:01:00:01/perf_mode"
    1: No such file or directory (os error 2)
```

running surface-kernel with Arch Linux: 
```
% uname -r
5.12.2-arch1-3-surface
```

I just installed Arch with the surface-kernel and thought it should work like this.
Did I do something wrong?

**Comment by qzed** [comment]
That interface has been replaced by the platform profile interface on 5.12 kernels, which is more generic and not just for Surface devices. So you need to use `surface profile` instead of `surface performance`.

Due to that you should now also be able to control it e.g. from Gnome settings with the power-profiles-daemon.

**Comment by PJungkamp** [comment]
Thank you!
